### ISSUE TITLE
Document types

### ISSUE THREAD

**Issue by 7deeptide** [psas/composite-propellant-tank#12]
Suggestion: Use markdown files or something else that GitHub can natively render where possible instead of non-free `.docx` files for project documentation.

**Comment by Wedon-Pete** [comment]
I can work on this as well, since I should have a documentation procedure finished up in the next couple days.  I did just add a pdf doc, and GitHub was able to render that pretty simply.  So, perhaps if we are creating documents in word, we can save them as a pdf before pushing them to Git

**Comment by natronics** [comment]
The idea of git is to hold the _source_ of whatever it is you're doing. Rather than having two versions (one word doc and one pdf) of every document, it's better if you just have one version. And it's much better if that document is plain text, like markdown so it's easy to read even for people who don't have Word installed. That will also let you see what changes over time inside the file.

**Comment by Wedon-Pete** [comment]
Ok, that's understandable... I'm still trying to figure this whole Git thing out.  Thanks

**Comment by Wedon-Pete** [comment]
Forgive me for being a little naive with all of this (so this could be a dumb question, but I'm asking anyway), but it seems that markdown is a formatting language.  Can we just use that in notepad?

**Comment by natronics** [comment]
Yes, that's right.

Anything plain text works great with git. If you add formatting like markdown, github and lots of other software will magically render it nicely. But what I mean is it should just be a text file.

**Comment by Wedon-Pete** [comment]
Ok, that's what I thought.  I found several simple markdown tutorials with a quick search, so I can go through those in the next week or so and see how hard it'll be to switch things over from the word docs we've already got.

Thanks for the input.

**Comment by Joedang** [comment]
There's a program called pandoc that will do this conversion for you. For example, you can give it the name of the input file and the name of the output file and it will figure out the rest.

```
$ pandoc Contacts.docx -o Contacts.md
```

As long as the content of the Word document isn't too crazy, it does what you'd expect. 

E: I made a branch with all the docx files converted to markdown. Some of the embedded images didn't make it through though. Hopefully that's useful for you guys.
