### ISSUE TITLE
Pump selection for hydrotesting tank

### ISSUE THREAD

**Issue by wilsoncw6** [psas/composite-propellant-tank#14]
Research hydrotesting pumps and create a document with vendor options.
Research hydrotesting procedures. Create a draft document.

**Comment by Wedon-Pete** [comment]
Thanks to work and some of my HVAC classes, I've got some experience figuring out pumps and can take this on...  I'll see what kind of preliminary info I can get in the next week or two.

**Comment by 7deeptide** [comment]
@wilsoncw6 @Wedon-Pete Apart from a test procedure, is this issue still open?
