### ISSUE TITLE
Stress analysis on Flat End Cap design

### ISSUE THREAD

**Issue by nab2** [psas/composite-propellant-tank#16]
Back of the envelope calculations & analysis on Flat end cap, to determine how thick it needs to be to meet FS=2, as well as any bolt sizing changes to meet FS.

**Comment by RussellCBerger** [comment]
This analysis needs to be checked for errors and validity
![20170419_161227](https://cloud.githubusercontent.com/assets/20232267/25206255/a71b032a-251b-11e7-8471-cc83f47c4ddd.jpg)

**Comment by wilsoncw6** [comment]
calculations are in Design\Analysis folder
