### ISSUE TITLE
Heat Transfer Analysis Refinement

### ISSUE THREAD

**Issue by nab2** [psas/composite-propellant-tank#17]
Further refining heat transfer analysis to better understand overall heat xfer through tank, better represent temperatures at each interface etc..

**Comment by alexkazam** [comment]
We will do the analysis with each layer experiencing the maximum change in temperature (30 C to about -190 C). Russell has already completed to analysis symbolically and used excel to determine numerical values. We will use jupyter notebook to verify the excel sheet.

**Comment by alexkazam** [comment]
See pressure vessel traditional thermal strain ipython notebook file in Analysis/Calculations folder.
