### ISSUE TITLE
Gasket/Template Laser Cutting

### ISSUE THREAD

**Issue by nab2** [psas/composite-propellant-tank#19]
Arrange time with MELT to get test PTFE cut to see if lasering gaskets is feasible.  Cut gaskets, cut templates for layup procedure

**Comment by andrewgreenberg** [comment]
DO NOT CUT PTFE ON THE LASER CUTTER, EVER.
Because Fluorine.

**Comment by andrewgreenberg** [comment]
Huh. On the other hand, some of the interwebz disagree with me. So I guess this should be investigated. This can't be cut in the LID, for sure, but maybe with the MELT laser venting it's OK? Proceed with extreme caution, I guess.

**Comment by nab2** [comment]
That was the idea.  Research done by Chris had shown that it may be ok to cut PTFE on the laser, we've been in contact with MELT already to arrange a time to do a test cut to determine if it will in fact be safe/work to our specifications.  If not we will switch to the mill or CNC.

**Comment by Joedang** [comment]
> maybe with the MELT laser venting it's OK?

If they turn down the pressure on the air for the cutting head, they could get a negative gauge pressure in the machine (if it's not that way already). So, air flowing into the seams instead of out. 

> we've been in contact with MELT already to arrange a time to do a test cut

Don't forget to try etching while you're at it. (Try engraving a cross-hatch pattern and a solid-fill raster, at least.)

**Comment by nab2** [comment]
> Don't forget to try etching while you're at it. (Try engraving a cross-hatch pattern and a solid-fill raster, at least.)

Hm interesting point Joe.  So try to laser etch the surface for adhesion as opposed to the chemical etching we have been working with already?

**Comment by Joedang** [comment]
Yeah, it wouldn't take long to try and might save a lot of time if it works.

**Comment by nab2** [comment]
> Don't forget to try etching while you're at it. (Try engraving a cross-hatch pattern and a solid-fill raster, at least.)
Hm interesting point Joe. So try to laser etch the surface for adhesion as opposed to the chemical etching we have been working with already?

> Yeah, it wouldn't take long to try and might save a lot of time if it works.

@wilsoncw6

**Comment by wilsoncw6** [comment]
Now that we have our PTFE sheet not just the gasket sheet I will explore this.

**Comment by nab2** [comment]
> Now that we have our PTFE sheet not just the gasket sheet I will explore this.

Great thanks Chris, I think just hand cutting the sheets with a template would be ok, but would be nice to get 'exact' dimensions as this is our inner liner.  My only concern is how any of the potential etching surface will interact with the laser since we know the PTFE should be fine.  Wouldn't want any excess chemical etching stuff burning off if it is still present on that surface.

**Comment by alexkazam** [comment]
Gasket design rejected.
