### ISSUE TITLE
Keg Ball-Lock Connector Fittings?

### ISSUE THREAD

**Issue by nab2** [psas/composite-propellant-tank#22]
Investigate using these type of fitting instead of current selection

**Comment by Joedang** [comment]
If you include things like 

* what you want to solve / why this is a problem
* suggestions for how to solve the problem
* criteria for closing the issue
* links to / sketches of the thing you're talking about
* tagging/assigning people who might be able to help

it may help people jump on the issue.

**Comment by nab2** [comment]
Gotcha, I'll hold off on updating more until it is a little more defined then.  This was more of a list being generated for our capstone group specifically to consolidate issues as opposed to our previous method.

**Comment by Joedang** [comment]
>I'll hold off on updating more until it is a little more defined then.

I mean, having the issues made is better than not having them. I just know it's easy to forget why something was a problem, how I planned to solve it, etc.

**Comment by wilsoncw6** [comment]
Did not use
