### ISSUE TITLE
Gasket/Bolt Analysis and Selection 

### ISSUE THREAD

**Issue by RussellCBerger** [psas/composite-propellant-tank#28]

**Comment by RussellCBerger** [comment]
Please review this for errors/validity
![20170419_162006](https://cloud.githubusercontent.com/assets/20232267/25206401/a3227b58-251c-11e7-9fc8-96c8955d7694.jpg)
![20170419_162021](https://cloud.githubusercontent.com/assets/20232267/25206402/a329db6e-251c-11e7-97ba-d2ae70abaaaf.jpg)

**Comment by RussellCBerger** [comment]
I have the hard copies, which will be converted into a jupyter notebook file when I have time

**Comment by nab2** [comment]
Closed, design rejected
