### ISSUE TITLE
Optimize Shrink-fit endcap / Compressed PTFE Design

### ISSUE THREAD

**Issue by FrancescaFr** [psas/composite-propellant-tank#29]
-Need to determine ideal thickness of PTFE liner and corresponding initial endcap inset diameter that preserves mechanical seal during chill and fill process. 
-Need to find reliable Elastic Mod and stress/strain behavior for given PTFE material at room and Cryo temps.
(Waiting on Manufacturer)
-Create optimization and FEA model for given interface.

**Comment by alexkazam** [comment]
See shrink fit calc excel sheet in Design/Analysis/Calculations folder
